import os
from pathlib import Path

def combine_python_files(directory: str, output_file: str = "combined.txt") -> None:
    """
    Combines all Python files in the given directory into a single text file.

    Args:
        directory (str): Path to the directory containing Python files.
        output_file (str): Path to the output file where the combined content will be saved.
    """
    # Ensure the directory exists
    dir_path = Path(directory)
    if not dir_path.is_dir():
        raise NotADirectoryError(f"The provided path '{directory}' is not a valid directory.")

    # Find all Python files in the directory (ignoring __pycache__ and non-.py files)
    python_files = [
        file for file in dir_path.glob("*.py") if "__pycache__" not in file.parts
    ]

    # Write to the output file
    with open(output_file, "w", encoding="utf-8") as out:
        out.write("# Combined Python Files\n")
        out.write("# Generated by combine_python_files script\n\n")

        for file in python_files:
            with open(file, "r", encoding="utf-8") as f:
                lines = f.readlines()

            # Write file header
            out.write(f"# {file.name}\n")
            out.writelines(lines)
            out.write("\n\n")

if __name__ == "__main__":
    # Example usage: Combine files in the current directory
    combine_python_files(directory=".")
